h1 : 'Hello everyone'
thumbnail : 'sea-side-city.jpg'
title : 'Hello everyone'
created_at : 2022-12-14T21:59+1:00
updated_at : 2022-12-17T20:03+1:00
tags :
    - presentation
    - tutorial
    - programming 101
