h1 : 'First things first'
thumbnail : 'desert.webp'
title : 'First things first'
created_at : 2022-12-14T21:59+1:00
updated_at : 2022-12-17T20:03+1:00
tags :
    - programming 101
    - programming
author : Jane Doe
